# Java & Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Minecraft + Forge
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
forge_version=47.4.0
forge_version_range=[47,)
loader_version_range=[46,)

# Cuffed Mod Dependency
# Project ID: 899770 (Cuffed)
# File ID: 6047857 (v1.3.9 for 1.20.1)
cuffed_maven=899770:7295282
cuffed_version_range=[1.3.9,)
# Lazr's Lib Dependency (Required by Cuffed)
# Project ID: 1048285 (Lazr's Lib)
# File ID: 5654672 (v1.1.1 for 1.20.1)
lazrslib_maven=899770:8094298
lazrslib_version_range=[1.1.1,)

# Mappings
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1

# Mixin
mixingradle_version=0.7-SNAPSHOT
mixin_version=0.8.5

# Mod Metadata
mod_id=cuffedplus
mod_name=cuffedplus
mod_license=All Rights Reserved
mod_version=1.0.0
mod_group_id=git.david.cuffedplus
mod_authors=David
mod_description=Addon for the Cuffed mod
