package git.david.cuffedplus.constants;

public class ConfigIDS {

    public static String KEEP_LOCKED_GEAR_ON_DEATH = "KEEP_LOCKED_GEAR_ON_DEATH";
    public static String CAN_PRISONER_ATTACK_PLAYERS_WITHOUT_ROLE = "CAN_PRISONER_ATTACK_PLAYERS_WITHOUT_ROLE";
    public static String ALLOW_BREAKING_TIME_LOCKED_RESTRAINTS = "ALLOW_BREAKING_TIME_LOCKED_RESTRAINTS";
    public static String SHOW_INFO_MESSAGES = "SHOW_INFO_MESSAGES";
    public static String SHOW_SUCCESS_MESSAGES = "SHOW_SUCCESS_MESSAGES";
    public static String SHOW_FAIL_MESSAGES = "SHOW_FAIL_MESSAGES";
    public static String PUT_PLAYERS_IN_CREATIVE_WHEN_ANTIGOD_RESTRAINTS_TIME_LOCK_RUNS_OUT = "PUT_PLAYERS_IN_CREATIVE_WHEN_ANTIGOD_RESTRAINTS_TIME_LOCK_RUNS_OUT";
    public static String ALLOW_EXECUTE_COMMANDS_WHILE_RESTRAINED = "ALLOW_EXECUTE_COMMANDS_WHILE_RESTRAINED";
    public static String ALLOW_PRISONERS_EXECUTE_COMMANDS = "ALLOW_PRISONERS_EXECUTE_COMMANDS";


    public static String SHOW_ROLE_PREFIX = "SHOW_ROLE_PREFIX";
    public static String ROLE_PREFIX_BOLD = "ROLE_PREFIX_BOLD";
    public static String PRISONER_ROLE_PREFIX = "PRISONER_ROLE_PREFIX";
    public static String OFFICER_ROLE_PREFIX = "OFFICER_ROLE_PREFIX";

    public static String OTHER_PLAYERS_JUMPSUIT_BEHAVIOR = "OTHER_PLAYERS_JUMPSUIT_BEHAVIOR";
    public static String OTHER_PLAYERS_ANKLE_MONITOR_BEHAVIOR = "OTHER_PLAYERS_ANKLE_MONITOR_BEHAVIOR";
    public static String PLAYERS_OWN_JUMPSUIT_LOCK_BEHAVIOR = "PLAYERS_OWN_JUMPSUIT_LOCK_BEHAVIOR";
    public static String PLAYERS_OWN_ANKLE_MONITOR_LOCK_BEHAVIOR = "PLAYERS_OWN_ANKLE_MONITOR_LOCK_BEHAVIOR";
    public static String OTHER_PLAYERS_JUMPSUIT_LOCK_BEHAVIOR = "OTHER_PLAYERS_JUMPSUIT_LOCK_BEHAVIOR";
    public static String OTHER_PLAYERS_ANKLE_MONITOR_LOCK_BEHAVIOR = "OTHER_PLAYERS_ANKLE_MONITOR_LOCK_BEHAVIOR";
    public static String PLAYERS_OWN_TRACKER_BINDING_BEHAVIOR = "PLAYERS_OWN_TRACKER_BINDING_BEHAVIOR";
    public static String OTHER_PLAYERS_TRACKER_BINDING_BEHAVIOR = "OTHER_PLAYERS_TRACKER_BINDING_BEHAVIOR";
    public static String PLAYERS_ATTACK_BEHAVIOR = "PLAYERS_ATTACK_BEHAVIOR";

    public static String ONLY_ALLOW_OFFICERS_TO_PUT_ON_GEAR = "ONLY_ALLOW_OFFICERS_TO_PUT_ON_GEAR";
    public static String ONLY_ALLOW_OFFICERS_TO_LOCK_GEAR = "ONLY_ALLOW_OFFICERS_TO_LOCK_GEAR";
    public static String ONLY_ALLOW_OFFICERS_TO_USE_RESTRAINTS = "ONLY_ALLOW_OFFICERS_TO_USE_RESTRAINTS";

    public static String OTHER_PRISONERS_JUMPSUIT_BEHAVIOR = "OTHER_PRISONERS_JUMPSUIT_BEHAVIOR";
    public static String OTHER_PRISONERS_ANKLE_MONITOR_BEHAVIOR = "OTHER_PRISONERS_ANKLE_MONITOR_BEHAVIOR";
    public static String PRISONERS_OWN_JUMPSUIT_LOCK_BEHAVIOR = "PRISONERS_OWN_JUMPSUIT_LOCK_BEHAVIOR";
    public static String PRISONERS_OWN_ANKLE_MONITOR_LOCK_BEHAVIOR = "PRISONERS_OWN_ANKLE_MONITOR_LOCK_BEHAVIOR";
    public static String OTHER_PRISONERS_JUMPSUIT_LOCK_BEHAVIOR = "OTHER_PRISONERS_JUMPSUIT_LOCK_BEHAVIOR";
    public static String OTHER_PRISONERS_ANKLE_MONITOR_LOCK_BEHAVIOR = "OTHER_PRISONERS_ANKLE_MONITOR_LOCK_BEHAVIOR";
    public static String PRISONERS_OWN_TRACKER_BINDING_BEHAVIOR = "PRISONERS_OWN_TRACKER_BINDING_BEHAVIOR";
    public static String OTHER_PRISONERS_TRACKER_BINDING_BEHAVIOR = "OTHER_PRISONERS_TRACKER_BINDING_BEHAVIOR";
    public static String PRISONERS_ATTACK_BEHAVIOR = "PRISONERS_ATTACK_BEHAVIOR";

    public static String Test = "Test";

}
